<html>
    <head>
        <title>We're pretty busy!</title>
        <link rel='dns-prefetch' href='//fonts.googleapis.com' />
        <link rel='stylesheet' id='sonassi-fonts-css'  href='https://fonts.googleapis.com/css?family=Open+Sans%7CTitillium+Web%3A700&#038;subset=latin%2Clatin-ext' type='text/css' media='all' />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="refresh" content="15" />
        <style>
            body { font-family: 'Open Sans', sans-serif; text-align: center; color: #333; background-color:#EFEFEF; }
            h1,h2,h3 { font-family: 'Titillium Web', sans-serif; font-size: 36px; font-weight: 700; color: #1B2D39; margin: 1em 0; }
            .metrics { color: #F24F4A; font-size: 1.5em; border: 1px solid #C0C0C0; }
            .metrics span { font-size: 60%; color: #888; }
            .block { display:block; }
        </style>
    </head>
    <body>

    <div class="container-fluid w-100 bg-white pb-5 mt-sm-5">
      <div class="row justify-content-center align-items-center">
        <div class="row justify-content-center">
            <div class="col-10 col-md-6">
                <h1>We are pretty busy!</h1>
                <p>Our site is pretty busy right now, but please hold on and you'll get in soon. This page will refresh automatically, keep this page open or you may lose your slot.</p>

                <div class="row mt-5 px-5 py-3 metrics">
                    <div class="col-12 col-sm-6">
                            <span class="block">Position</span>
                            {{queue.position}} <span>/ {{queue.total}}</span>
                    </div>
                    <div class="col-12 col-sm-6">
                            <span class="block">ETA</span>
                            {{queue.eta}} <span> minutes</span>
                    </div>
                </div>
            </div>
        </div>
      </div>
    </div>

    <script type="text/javascript">
        var wcIsGtm = false;
        var productImpressions = [];
        var promoImpressions = [];
        var wcGuaTrackerName = '';

        (function(w,e,b,c,oo,ki,ng){w['GoogleAnalyticsObject']=oo;w[oo]=w[oo]||function(){
            (w[oo].q=w[oo].q||[]).push(arguments)},w[oo].l=1*new Date();ki=e.createElement(b),
            ng=e.getElementsByTagName(b)[0];ki.async=1;ki.src=c;ng.parentNode.insertBefore(ki,ng)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', '{{ga_code}}', 'auto');
        ga('set', 'page', 'Queue');
        ga('send', 'pageview');
    </script>
  </body>
</html>