<html>
    <head>
        <title>Our site is pretty busy</title>
        <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet" />

       <style>
           body { font-family: 'Muli', sans-serif; text-align: center; background-color:#EFEFEF; }
           h1 { font-size: 50px; }
           input[type='submit'] { padding: 10px 20px; font-size: 18px; margin: 0 auto; display: block; cursor: pointer; }
           form { margin-top: 50px; }
           .main-div { background-color:white; margin-top:150px; padding:20px 50px 50px 50px; }
           .pos { color: #ab4324; font-size: 25px; font-weight: 800; border: 1px solid #C0C0C0; width: 50px; height: 35px; text-align: center; display: inline-block; }

       </style>

       <meta http-equiv="refresh" content="60" />

    </head>
    <body>
       <div class="main-div">

            <h1>We are pretty busy!</h1>

            <p>Our site is pretty busy right now, but keep clicking below to get in and shop!</p>
            <p>This page will refresh automatically, don't close the page so you don't lose your slot</p>

            <p>Your position in the queue: <big class="pos">{{queue_position}}</big></p>

            <form action="" method="POST">
                <input type="hidden" name="referrer" value="<?php echo $_SERVER['REQUEST_URI']; ?>" />
                <input type="submit" class="submit-button" name="retry" value="Try again" />
            </form>

       </div>
</body>
</html>
